[package]
name = "pod-mod-podgo"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
hibitset = "0.6.3"

once_cell = "*" # defined in pod-core
maplit = "*" # defined in pod-mod-pod2
log = "*" # defined in pod-core
tokio = "*" # defined in pod-core
anyhow = "*" # defined in pod-code
serde = { version = "1", features = ["derive"] }
toml = "0.8"

pod-core = { path = "../core" }
pod-usb = { path = "../usb" }
pod-gtk = { path = "../gtk" }
pod-mod-pod2 = { path = "../mod-pod2" }
pod-mod-xt = { path = "../mod-xt" }